# Generated by Django 3.0.4 on 2020-06-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemspinhistory',
            name='item_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemspinhistory',
            name='spin_type',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
