# Generated by Django 3.0.4 on 2020-06-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200604_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemspinhistory',
            name='t_open_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
