# Generated by Django 3.0.4 on 2020-06-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20200603_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login',
        ),
    ]
