# Generated by Django 3.0.4 on 2020-06-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_auto_20200603_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='t_open_id',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
